# This workflow is for a project that using curly-eureka sdk
name: Build mod on curly-eureka
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  CE_INCL: '${{github.workspace}}/sdk/CURLY-EUREKA-INCL.cmake'
jobs:
  main:
    runs-on: windows-latest
    steps:
    - name: this repo
      uses: actions/checkout@v3
    - name: curly-eureka sdk repo 
      uses: actions/checkout@v3
      with: 
       repository: 'user95401/curly-eureka'
       path: 'sdk'
    - name: configure cmake
      run: cmake -B build -A win32
    - name: build
      run: cmake --build build --config Release
    - uses: actions/upload-artifact@v4
      with:
       name: "built dlls"
       path: "*/*.dll"
